### ISSUE TITLE
Function "populate" undefined

### ISSUE THREAD

**Issue by paolino68** [haiflive/orientdb-yii2-connector#4]
In Query::all() the ` $this->populate($rows);` call an undefined function.

**Comment by haiflive** [comment]
fixed

thanks for the feedback

**Comment by SimonSoftware** [comment]
Sorry but now using
```
<?php
namespace backend\controllers;

use OrientDBYii2Connector\ActiveQuery;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;


use PhpOrient\PhpOrient;
use PhpOrient\Protocols\Binary\Data\Record;
use OrientDBYii2Connector\Query;
use OrientDBYii2Connector\DataRreaderOrientDB;
/**
 * Site controller
 */
class TestController extends Controller
{

  public function actionIndex() {
      echo "OK";
  }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionOrient()
    {
      $client = Yii::$app->dborient;
      //$eee = $client->command('select from beer');
      //var_dump($eee);
      //die();
      /*
      $recordContent = [ 'accommodation' => 'houses', 'work' => 'bazar', 'holiday' => 'sea' ];
      $rec = ( new Record() )->setOData( $recordContent )->setRid( new ID( 9 ) );
      $record = $client->recordCreate( $rec );
*/

      /* $client = Yii::$app->dborient->createCommand(); */
      /*$sql = $client->insert('beer', [
        'name' => 'test2',
      ])->execute();*/
      $testQ = (new Query())
        // ->select('name', 'descript', 'out_HasCategory.in.exclude(\'in_HasCategory\')')
        //->select('name, descr')
        ->from('beer')
        // ->limit(2)
        // ->where(['name' => 'Hocus Pocus'])
        //->fetch_plan(['out_HasCategory.in:0', 'out_HasBrewery.in:0', 'out_HasStyle.in:0'])
        // ->limit(10)
        // ->exists(Yii::$app->dborient);
        ->all(Yii::$app->dborient);


      // use tree builder(associate records and relations)
      $data = (new DataRreaderOrientDB($testQ))->getTree();
      //var_dump($data);

      // result:
      echo json_encode($data);
      //$testQ = (new Query())->from('V')->all(Yii::$app->dborient);

    }
}

```

 i have:


`Exception
Unknown Property – yii\base\UnknownPropertyException

Setting unknown property: OrientDBYii2Connector\DataRreaderOrientDB::0
1. in /Applications/MAMP/htdocs/bestofmylife/website/vendor/yiisoft/yii2/base/Component.php at line 201
192193194195196197198199200201202203204205206207208209210                $behavior->$name = $value;
                return;
            }
        }
 
        if (method_exists($this, 'get' . $name)) {
            throw new InvalidCallException('Setting read-only property: ' . get_class($this) . '::' . $name);
        }
 
        throw new UnknownPropertyException('Setting unknown property: ' . get_class($this) . '::' . $name);
    }
 
    /**
     * Checks if a property is set, i.e. defined and not null.
     * This method will check in the following order and act accordingly:
     *
     *  - a property defined by a setter: return whether the property is set
     *  - a property of a behavior: return whether the property is set
     *  - return `false` for non existing properties
2. in /Applications/MAMP/htdocs/bestofmylife/website/vendor/yiisoft/yii2/BaseYii.php at line 529 – yii\base\Component::__set('0', ['name' => 'test2', '@rid' => '#21:1', '@version' => 1, '@class' => 'Beer'])
3. in /Applications/MAMP/htdocs/bestofmylife/website/vendor/yiisoft/yii2/base/Object.php at line 105 – yii\BaseYii::configure(OrientDBYii2Connector\DataRreaderOrientDB, [['name' => 'test2', '@rid' => '#21:1', '@version' => 1, '@class' => 'Beer'], ['name' => 'test2', '@rid' => '#21:2', '@version' => 1, '@class' => 'Beer'], ['name' => 'test2', '@rid' => '#21:3', '@version' => 1, '@class' => 'Beer'], ['descr' => 'aaa', '@rid' => '#21:4', '@version' => 1, '@class' => 'Beer'], ...])
4. in /Applications/MAMP/htdocs/bestofmylife/website/backend/controllers/TestController.php at line 60 – yii\base\Object::__construct([['name' => 'test2', '@rid' => '#21:1', '@version' => 1, '@class' => 'Beer'], ['name' => 'test2', '@rid' => '#21:2', '@version' => 1, '@class' => 'Beer'], ['name' => 'test2', '@rid' => '#21:3', '@version' => 1, '@class' => 'Beer'], ['descr' => 'aaa', '@rid' => '#21:4', '@version' => 1, '@class' => 'Beer'], ...])
54555657585960616263646566        // ->limit(10)
        // ->exists(Yii::$app->dborient);
        ->all(Yii::$app->dborient);
 
 
      // use tree builder(associate records and relations)
      $data = (new DataRreaderOrientDB($testQ))->getTree();
      //var_dump($data);
 
      // result:
      echo json_encode($data);
      //$testQ = (new Query())->from('V')->all(Yii::$app->dborient);
 
5. backend\controllers\TestController::actionOrient()
6. in /Applications/MAMP/htdocs/bestofmylife/website/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([backend\controllers\TestController, 'actionOrient'], [])
7. in /Applications/MAMP/htdocs/bestofmylife/website/vendor/yiisoft/yii2/base/Controller.php at line 156 – yii\base\InlineAction::runWithParams([])
8. in /Applications/MAMP/htdocs/bestofmylife/website/vendor/yiisoft/yii2/base/Module.php at line 523 – yii\base\Controller::runAction('orient', [])
9. in /Applications/MAMP/htdocs/bestofmylife/website/vendor/yiisoft/yii2/web/Application.php at line 102 – yii\base\Module::runAction('test/orient', [])
10. in /Applications/MAMP/htdocs/bestofmylife/website/vendor/yiisoft/yii2/base/Application.php at line 380 – yii\web\Application::handleRequest(yii\web\Request)
11. in /Applications/MAMP/htdocs/bestofmylife/website/backend/web/index.php at line 17 – yii\base\Application::run()
11121314151617    require(__DIR__ . '/../../common/config/main.php'),
    require(__DIR__ . '/../../common/config/main-local.php'),
    require(__DIR__ . '/../config/main.php'),
    require(__DIR__ . '/../config/main-local.php')
);
 
(new yii\web\Application($config))->run();
 Yii Framework
2017-07-07, 16:24:29

Apache
Yii Framework/2.0.12
2.0.12 PHP 7.1.1 Status 500 Route test/orient Log 25  1 Time 11,809 ms Memory 5.875 MB DB 1 17 ms
`

**Comment by paolino68** [comment]
Maybe the problem was all the lines like this
`(new DataRreaderOrientDB($command->queryOne()))->getTree();`
in Query.php.

In the example i can't recall DataRreaderOrientDB twice. 

This work:

```

public function all($db = null)
    {
        $command = $this->createCommand($db);
        if(!empty($this->fetch_plan))
            $command->setFetch_plan($this->fetch_plan);
        //$rows = (new DataRreaderOrientDB($command->queryAll()))->getTree();
        $rows = $command->queryAll();
        return $this->populate($rows);
    }

public function one($db = null)
    {
        $this->limit = 1;
        $command = $this->createCommand($db);
        if(!empty($this->fetch_plan)){
            $command->setFetch_plan($this->fetch_plan);
           //$rows = (new DataRreaderOrientDB($command->queryOne()))->getTree();
            $rows = $command->queryOne();
            if(!empty($rows) && !empty($rows['records'][0]))
                return $rows['records'][0];
        } else {
            $rows = $command->queryOne();
            if(isset($rows['records'][0])) {
//               return DataRreaderOrientDB::getRecordData($rows['records'][0]);
              return $rows['records'][0];
            }
        }
        
        return null;
    }


```

**Comment by haiflive** [comment]
You do not need to use DataRreaderOrientDB any more, it used by default, I will upgrade documentation later;

just use as is
```
$testQ = (new Query())
        ->from('beer')
        ->all();

foreach($testQ as $record) {
        // do something
}
```

**Comment by haiflive** [comment]
Documentation upgraded, I think it would be helpful to use this lib

thanks for the feedback
