### ISSUE TITLE
DELETE syntax

### ISSUE THREAD

**Issue by SimonSoftware** [haiflive/orientdb-yii2-connector#5]
In QueryBuilder.php the right DELETE syntax is without FROM like:

`$sql = 'DELETE ' . $type . ' ' . $this->db->quoteTableName($table);`

and not 
`$sql = 'DELETE '. $type .' FROM ' . $this->db->quoteTableName($table);`

From documentation page https://orientdb.com/docs/2.2/Console-Command-Delete.html

NOTE: When dealing with vertices and edges, do not use the standard SQL DELETE command. Doing so can disrupt graph integrity. Instead, use the DELETE VERTEX or the DELETE EDGE commands.

**Comment by haiflive** [comment]
fixed
